### ISSUE TITLE
Random variables set when updating

### ISSUE THREAD

**Issue by PooreH** [Tom-evnut/TeslaBMSV2#23]
Tom, any consideration for an export/import of the configuration. Recent issue wrote a new value to the (I)nore option which disabled my temp readings. 

Being able to export existing configuration, zero all variables, and then import after an upgrade would reduce weirdness. Otherwise it’s manually record all settings, upgrade, and manually check all settings.

**Comment by Tom-evnut** [comment]
Gotten the back end coded up to Output all the settings in a format that can be read back in via a file upload using a serial program like YAT serial terminal.

Only open point is making the inputting of variables a lot more robust, this will be done by checking plausibility for each parameter. Current program contains 68 so its going to take a bit of time.
